warn if key commands not found

diff --git a/.me/50task b/.me/50task
--- a/.me/50task
+++ b/.me/50task
@@ -1,3 +1,6 @@
+if ! which task > /dev/null 2>&1 ; then
+  echo \'task\' command not found
+fi
 alias t=task
 
 # vim: ft=zsh
