formatting improvements

diff --git a/share/templates/bash b/share/templates/bash
--- a/share/templates/bash
+++ b/share/templates/bash
@@ -1,30 +1,34 @@
 #!/usr/bin/env bash
 
+prog=$(basename $0)
+
+indent="    "
+
 usage() {
     echo
     echo "USAGE"
     echo
-    echo -e "\t$(basename $0) [options] <reqd_arg> [opt_arg]"
+    echo "${indent}$prog [options] <reqd_arg> [opt_arg]"
     echo
     echo "WHERE"
     echo
-    echo -e "\targ\tdescription"
+    echo -e "${indent}arg\tdescription"
     echo
     echo "DESCRIPTION"
     echo
-    echo -e "\t..."
+    echo "${indent}..."
     echo
     echo "OPTIONS"
     echo
-    echo -e "\t-h\tdisplay this message"
+    echo -e "${indent}-h\tdisplay this message"
     echo
     echo "NOTES"
     echo
-    echo -e "\tif applicable"
+    echo "${indent}if applicable"
     echo
     echo "SEE ALSO"
     echo
-    echo -e "\tif applicable"
+    echo "${indent}if applicable"
     echo
     echo
 }
@@ -36,12 +40,12 @@ while getopts ":h" opt ; do
             exit
             ;;
         :)
-            echo "$opt requires an argument" >&2
+            echo "-$OPTARG requires an argument" >&2
             echo "run with -h for help" >&2
             exit 1
             ;;
         \?)
-            echo "invalid option $opt" >&2
+            echo "invalid option -$OPTARG" >&2
             echo "run with -h for help" >&2
             exit 1
             ;;
